name: publish

on: push

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - name: Invoke workflow in ymath-io/ymath.io
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: cd
          repo: ymath-io/ymath.io
          token: ${{ secrets.PERSONAL_TOKEN }}

