backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
site_url: https://dev.ymath.io
display_url: https://dev.ymath.io
logo_url: https://dev.ymath.io/favicon.png

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false

  - name: 'courses'
    label: 'Courses'
    format: 'frontmatter'
    folder: 'content/courses'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'index', name: 'date', widget: 'number' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

